name: SERVER distribute  # 알아서 이름 지으면 된다. 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/ezhome-web
            sudo git pull
            sudo yarn
            sudo yarn build
            pm2 reload all
